from __future__ import annotations
from typing import Protocol, Callable, Optional, Tuple
from dataclasses import dataclass
import jax, jax.numpy as jnp
from jax import Array
from typing_extensions import Protocol

from gaussed.linops.base import LinearOperator


class Engine(Protocol):
    def solve(self, A: LinearOperator, b: Array) -> Array: ...
    def logdet(self, A: LinearOperator) -> float: ...
    def trace(self, A: LinearOperator) -> float: ...
    def quadratic_form(self, A: LinearOperator, x: Array) -> float: ...
    def sample(self, A: LinearOperator, key: Array) -> Array: ...